# Generated by Django 5.2.8 on 2025-11-06 18:35

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Local')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cor', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Cor de Identificação')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Equipamento')),
                ('tipo', models.CharField(choices=[('SW', 'Switch'), ('RT', 'Roteador'), ('AP', 'Access Point'), ('SR', 'Servidor'), ('OT', 'Outro')], max_length=2, verbose_name='Tipo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série')),
                ('ip_gerencia', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP de Gerência')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuário')),
                ('senha', models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha')),
                ('andar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Andar')),
                ('sala', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sala')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de Instalação')),
                ('garantia_ate', models.DateField(blank=True, null=True, verbose_name='Garantia Até')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rede.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['localizacao', 'tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREV', 'Preventiva'), ('CORR', 'Corretiva'), ('MELH', 'Melhoria'), ('CONF', 'Configuração'), ('OUTR', 'Outra')], max_length=4, verbose_name='Tipo de Manutenção')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Término')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('acoes_realizadas', models.TextField(verbose_name='Ações Realizadas')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='rede.equipamento')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PortaSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)], verbose_name='Número da Porta')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('porta_equipamento', models.CharField(blank=True, help_text='Número/Identificação da porta no equipamento conectado', max_length=50, null=True, verbose_name='Porta do Equipamento')),
                ('vlan', models.CharField(blank=True, max_length=50, null=True, verbose_name='VLAN')),
                ('velocidade', models.CharField(blank=True, help_text='Ex: 100Mbps, 1Gbps, 10Gbps', max_length=20, null=True, verbose_name='Velocidade')),
                ('duplex', models.CharField(blank=True, choices=[('half', 'Half-Duplex'), ('full', 'Full-Duplex')], max_length=20, null=True, verbose_name='Duplex')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('equipamento', models.ForeignKey(limit_choices_to={'tipo': 'SW'}, on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='rede.equipamento')),
                ('equipamento_conectado', models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['RT', 'AP', 'SR', 'OT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porta_conectada', to='rede.equipamento', verbose_name='Equipamento Conectado')),
            ],
            options={
                'verbose_name': 'Porta de Switch',
                'verbose_name_plural': 'Portas de Switch',
                'ordering': ['equipamento', 'numero'],
                'unique_together': {('equipamento', 'numero')},
            },
        ),
    ]
