# Generated by Django 5.2.8 on 2025-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('SW', 'Switch'), ('RT', 'Roteador'), ('AP', 'Access Point'), ('SR', 'Servidor'), ('PC', 'PC Desktop'), ('NB', 'Notebook'), ('OT', 'Outro')], max_length=2, verbose_name='Tipo'),
        ),
    ]
