# Generated by Django 5.2.8 on 2025-11-07 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0002_alter_equipamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaswitch',
            name='equipamento_conectado',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['RT', 'AP', 'SR', 'PC', 'NB', 'OT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porta_conectada', to='rede.equipamento', verbose_name='Equipamento Conectado'),
        ),
    ]
