# Generated by Django 5.2.8 on 2025-11-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0003_alter_portaswitch_equipamento_conectado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portaswitch',
            options={'ordering': ['equipamento', 'numero'], 'verbose_name': 'Porta de Equipamento de Rede', 'verbose_name_plural': 'Portas de Equipamentos de Rede'},
        ),
        migrations.AlterField(
            model_name='portaswitch',
            name='equipamento',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ['SW', 'RT']}, on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='rede.equipamento', verbose_name='Equipamento de Rede'),
        ),
        migrations.AlterField(
            model_name='portaswitch',
            name='equipamento_conectado',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['SW', 'RT', 'AP', 'SR', 'PC', 'NB', 'OT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porta_conectada', to='rede.equipamento', verbose_name='Equipamento Conectado'),
        ),
    ]
