# Generated by Django 5.2.8 on 2025-11-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0004_alter_portaswitch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaswitch',
            name='tipo_conexao',
            field=models.CharField(blank=True, choices=[('', 'Nenhum'), ('TX', 'Transmissão (TX) - Fornece internet'), ('RX', 'Recepção (RX) - Recebe internet')], help_text='Indica se a porta está fornecendo (TX) ou recebendo (RX) internet', max_length=2, null=True, verbose_name='Tipo de Conexão'),
        ),
    ]
