# Generated by Django 5.2.8 on 2025-11-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0005_portaswitch_tipo_conexao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaswitch',
            name='porta_equipamento',
        ),
    ]
