# Generated by Django 5.2.8 on 2025-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0006_remove_portaswitch_porta_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaswitch',
            name='velocidade',
            field=models.CharField(blank=True, choices=[('100M', '100Mbps'), ('1G', '1Gbps'), ('10G', '10Gbps'), ('25G', '25Gbps'), ('40G', '40Gbps'), ('100G', '100Gbps'), ('OUTRA', 'Outra')], help_text='Velocidade da porta de rede', max_length=5, null=True, verbose_name='Velocidade'),
        ),
    ]
