# Generated by Django 5.2.8 on 2025-11-11 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0007_alter_portaswitch_velocidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='porta',
            field=models.PositiveIntegerField(blank=True, help_text='Porta de acesso ao equipamento (1-65535)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Porta de Acesso'),
        ),
    ]
