# Generated by Django 5.2.8 on 2025-11-11 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0008_equipamento_porta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaswitch',
            name='numero',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número da Porta'),
        ),
    ]
